runmode: debug                 # 开发模式, debug, release, test
addr: :18080                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:18080     # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  addr: :18081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_apiserver
  addr: 127.0.0.1:20000
  username: root
  password: 123456
docker_db:
  name: db_apiserver
  addr: 127.0.0.1:20000
  username: root
  password: 123456
